server:
  port: 8080

spring:
  messages: #i18n国际化配置
    basename: i18n/index
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  #指定使用的数据源类型
    filters: stat
    maxActive: 20
    initialSize: 5  #连接池初始化大小
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  type-aliases-package: com.demo.springbootlog.entity
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true

logging:
  file: ./logs/test.log
  level:
    com.demo.shop.mapper: debug
    #com.capinfo.mapper: info

